development:
  secret_token: secretysecret
  secret_key_base: secretytwice

test:
  secret_token: secretysecret
  secret_key_base: secretytwice

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
